### ISSUE TITLE
Token Refresh

### ISSUE THREAD

**Issue by BrahimS** [ditrit/gandalf-core#222]
Regarding the "/refreshtoken" route, is it possible to return me in addition to the nx tocken, the user object [see captation](https://user-images.githubusercontent.com/7687826/170252961-4cc7b21f-df61-4f73-8b3c-286483ab4ccc.png)
 Thanks :)

**Comment by Zorin95670** [comment]
As we discussed, we don't want to retrieve user in the endpoint `/refreshtoken`.
